(part "E-L9637D"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "RX") (portType INOUT))
        (port "2" (symbPinId 2) (portName "LO") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VCC") (portType INOUT))
        (port "4" (symbPinId 4) (portName "TX") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND") (portType INOUT))
        (port "6" (symbPinId 6) (portName "K") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VS") (portType INOUT))
        (port "8" (symbPinId 8) (portName "LI") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "511-E-L9637D")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/E-L9637D?qs=lrqjml%252Bjt8d%2FUlnJz0Tlgg%3D%3D")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "E-L9637D")
    (property "Description" "Monolithic bus driver with ISO 9141 interface")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/l9637.pdf")
    (property "symbolName1" "E-L9637D")
)
